flask:
  image:
    repository: 816069136612.dkr.ecr.us-east-1.amazonaws.com/tech-consulting-final-project-app/flask-app
    tag: "V14"
  replicaCount: 1
  config:
    FLASK_ENV: "production"
    DATABASE_URL: "mysql://root:rootpassword@mysql:3306/taskdb"  # You can replace with actual MySQL connection string
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "250m"
      memory: "256Mi"

mysql:
  image:
    repository: 816069136612.dkr.ecr.us-east-1.amazonaws.com/tech-consulting-final-project-app/mysql-db
    tag: "V14"
  replicaCount: 1
  rootPassword: "rootpassword"  # Consider base64 encoding or using a Kubernetes secret
  database: "taskdb"
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "250m"
      memory: "256Mi"

services:
  flask:
    port: 80
    targetPort: 5000
    type: LoadBalancer
  mysql:
    port: 3306
    targetPort: 3306
    type: ClusterIP
