apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk  # base64 for "rootpassword"
  MYSQL_DATABASE: dGFza2Ri           # base64 for "taskdb"
